// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User_API.UserClasses;

namespace User_API.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20210118114933_InitialMigravionV1")]
    partial class InitialMigravionV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("User_API.UserClasses.MessageClass", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Body")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Subject")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userClassPassword")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MessageId");

                    b.HasIndex("userClassPassword");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("User_API.UserClasses.UserClass", b =>
                {
                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Password");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("User_API.UserClasses.MessageClass", b =>
                {
                    b.HasOne("User_API.UserClasses.UserClass", "userClass")
                        .WithMany("messageClasses")
                        .HasForeignKey("userClassPassword");

                    b.Navigation("userClass");
                });

            modelBuilder.Entity("User_API.UserClasses.UserClass", b =>
                {
                    b.Navigation("messageClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
